# sudo: required

os: linux

language: generic

dist: xenial

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t yeongbba/docker-react-app -f Dockerfile.dev ./docker-react-app-master

script:
  - docker run -e CI=true yeongbba/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"
